#### **Dependencies and constants**

In [117]:
import os
import random
import warnings

from datetime import date
from importlib import reload

import numpy as np
import pandas as pd
import plotly.express as px

from catboost import CatBoostRegressor
from dotenv import load_dotenv
from lightgbm import LGBMRegressor
from plotly.graph_objs import Figure
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import FunctionTransformer
from tqdm import tqdm
from xgboost import XGBRegressor

import src.ingest
import src.train
import src.transform
reload(src.ingest)
reload(src.train)
reload(src.transform)
from src.ingest import ingest_data, RAW_DATA_DIR, PREPROCESSED_DATA_DIR
from src.train import BaselineModel, get_rsquared, train_model
from src.transform import split_data, transform_data

warnings.filterwarnings("ignore")
load_dotenv()

True

In [2]:
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option('display.max_colwidth', None)

#### **Data ingestion**

In [3]:
# download, pre-process, and validate all raw data from 2022
# NOTE: the 'df' pd.DataFrame contains several univariate time series, where each ...
# (A) is in hourly time increments, ...
# (B) spans the entire year of 2022, and ...
# (C) corresponds to a unique pickup location ID
df: pd.DataFrame = ingest_data(2022)
df

100%|██████████| 12/12 [00:00<00:00, 5698.14it/s]

         pickup_location_id         pickup_hour  n_taxi_rides
0                         1 2022-01-01 04:00:00           1.0
1                         1 2022-01-01 05:00:00           1.0
2                         1 2022-01-01 06:00:00           0.0
3                         1 2022-01-01 07:00:00           2.0
4                         1 2022-01-01 08:00:00           0.0
...                     ...                 ...           ...
2117080                 265 2022-12-31 19:00:00           2.0
2117081                 265 2022-12-31 20:00:00           2.0
2117082                 265 2022-12-31 21:00:00           7.0
2117083                 265 2022-12-31 22:00:00           3.0
2117084                 265 2022-12-31 23:00:00           2.0

[2117085 rows x 3 columns]

In [4]:
# plot the number of hourly passengers in Jan 2022, for pickup location IDs 43, 100, and 233
location_ids: list[int] = [43, 100, 233]
px.line(
    df
    .loc[
        (df["pickup_location_id"].isin(sorted(location_ids))) & 
        (df["pickup_hour"] >= pd.to_datetime("2022-01-01")) & 
        (df["pickup_hour"] < pd.to_datetime("2022-02-01"))
    ], 
    x="pickup_hour", 
    y="n_taxi_rides", 
    color="pickup_location_id", 
    labels={
        "pickup_hour": "Datetime", 
        "n_taxi_rides": "Number of taxi rides", 
        "pickup_location_id": "Location ID"
    },
    template="plotly_dark"
)

#### **Data transformation**

In [5]:
# output the 'df' pd.DataFrame, which contains pre-processed and validated data
# NOTE: the 'df' pd.DataFrame contains several univariate time series, one per pickup location ID
df

         pickup_location_id         pickup_hour  n_taxi_rides
0                         1 2022-01-01 04:00:00           1.0
1                         1 2022-01-01 05:00:00           1.0
2                         1 2022-01-01 06:00:00           0.0
3                         1 2022-01-01 07:00:00           2.0
4                         1 2022-01-01 08:00:00           0.0
...                     ...                 ...           ...
2117080                 265 2022-12-31 19:00:00           2.0
2117081                 265 2022-12-31 20:00:00           2.0
2117082                 265 2022-12-31 21:00:00           7.0
2117083                 265 2022-12-31 22:00:00           3.0
2117084                 265 2022-12-31 23:00:00           2.0

[2117085 rows x 3 columns]

In [6]:
# transform the 'df' pd. DataFrame
# NOTE: each univariate time series in the 'df' pd.DataFrame, one per pickup location ID, ...
# will be transformed into a 2-D matrix of datetime features, window features, lag features, ...
# and the target, 'n_taxi_rides'
df_transformed: pd.DataFrame = transform_data(df)
df_transformed

100%|██████████| 262/262 [00:15<00:00, 16.71it/s]

,pickup_location_id,hour,time_of_day,mean_lags_24_to_1,mean_lags_20_to_1,mean_lags_16_to_1,mean_lags_12_to_1,mean_lags_8_to_1,mean_lags_4_to_1,lag_24,lag_23,lag_22,lag_21,lag_20,lag_19,lag_18,lag_17,lag_16,lag_15,lag_14,lag_13,lag_12,lag_11,lag_10,lag_9,lag_8,lag_7,lag_6,lag_5,lag_4,lag_3,lag_2,lag_1,n_taxi_rides
pickup_hour,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2022-01-02 04:00:00,1,4,4,1.791667,1.95,2.2500,1.000000,0.250,0.00,1.0,1.0,0.0,2.0,0.0,0.0,1.0,2.0,1.0,5.0,5.0,13.0,3.0,3.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022-01-02 05:00:00,1,5,1,1.750000,1.95,2.1875,0.750000,0.000,0.00,1.0,0.0,2.0,0.0,0.0,1.0,2.0,1.0,5.0,5.0,13.0,3.0,3.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
2022-01-02 06:00:00,1,6,1,1.875000,2.15,2.1250,0.833333,0.500,1.00,0.0,2.0,0.0,0.0,1.0,2.0,1.0,5.0,5.0,13.0,3.0,3.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0
2022-01-02 07:00:00,1,7,1,1.916667,2.15,1.8750,0.833333,0.625,1.25,2.0,0.0,0.0,1.0,2.0,1.0,5.0,5.0,13.0,3.0,3.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,2.0
2022-01-02 08:00:00,1,8,1,1.916667,2.15,1.1875,0.750000,0.875,1.75,0.0,0.0,1.0,2.0,1.0,5.0,5.0,13.0,3.0,3.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-31 19:00:00,265,19,3,3.291667,3.50,3.0625,2.916667,3.250,3.25,2.0,5.0,1.0,1.0,7.0,3.0,5.0,6.0,3.0,2.0,3.0,6.0,2.0,0.0,5.0,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0
2022-12-31 20:00:00,265,20,3,3.291667,3.25,3.0000,2.916667,2.875,2.75,5.0,1.0,1.0,7.0,3.0,5.0,6.0,3.0,2.0,3.0,6.0,2.0,0.0,5.0,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2.0
2022-12-31 21:00:00,265,21,4,3.166667,3.20,3.0000,3.083333,2.875,2.75,1.0,1.0,7.0,3.0,5.0,6.0,3.0,2.0,3.0,6.0,2.0,0.0,5.0,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2.0,7.0
2022-12-31 22:00:00,265,22,4,3.416667,3.30,3.2500,3.250000,3.500,3.50,1.0,7.0,3.0,5.0,6.0,3.0,2.0,3.0,6.0,2.0,0.0,5.0,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2.0,7.0,3.0
2022-12-31 23:00:00,265,23,4,3.500000,3.15,3.0625,3.333333,3.375,3.50,7.0,3.0,5.0,6.0,3.0,2.0,3.0,6.0,2.0,0.0,5.0,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2.0,7.0,3.0,2.0

In [7]:
# split the 'df_transformed' pd.DataFrame into two pd.DataFrames, ...
# one containing the lag features and the other containing the corresponding targets
features: pd.DataFrame = df_transformed.drop("n_taxi_rides", axis=1)
target: pd.DataFrame = df_transformed[["pickup_location_id", "n_taxi_rides"]]

**`Plotting a single record's lag features and target`**

In [9]:
# randomly extract a single record
location_id: int = random.choice(features["pickup_location_id"].unique())
idx: pd.Timestamp = random.choice(features.query(f"pickup_location_id == {location_id}").index)

# get the single record's lag features
x: pd.Series = (
    features
    .query(f"pickup_location_id == {location_id}")
    .drop("pickup_location_id", axis=1)
    .loc[idx, [col for col in features.columns if col.startswith("lag")]]
)
# get the single record's target
y: float = target.query(f"pickup_location_id == {location_id}").loc[idx, "n_taxi_rides"]

# get the single record's duration
duration: pd.DatetimeIndex = pd.date_range(idx - pd.Timedelta(hours=len(x)), idx, freq="H")

# plot the points that correspond to the lag features
fig: Figure = px.line(
    x=duration[:-1], 
    y=x, 
    labels={"x": "Datetime", "y": "Number of taxi rides"},
    template="plotly_dark", 
    markers=True, 
    title=f"Hourly taxi rides for location ID {location_id}"
)

# add the point that corresponds to the target
fig.add_scatter(
    x=duration[-1:], y=[y], line_color="green", mode="markers", marker_size=10, name="target"
)
fig.show()

#### **Train-test split**

In [10]:
# create the transformed data, that is, tabular data with features and a target 
df_transformed: pd.DataFrame = ingest_data(2022).pipe(transform_data)

100%|██████████| 12/12 [00:00<00:00, 6072.83it/s]
100%|██████████| 262/262 [00:16<00:00, 15.79it/s]

In [11]:
# split the data into train and test sets
Xtrain, ytrain, Xtest, ytest = split_data(df_transformed, "2022-10-01")

In [12]:
# train set
pd.concat((Xtrain, ytrain["n_taxi_rides"]), axis=1)

,pickup_location_id,hour,time_of_day,mean_lags_24_to_1,mean_lags_20_to_1,mean_lags_16_to_1,mean_lags_12_to_1,mean_lags_8_to_1,mean_lags_4_to_1,lag_24,lag_23,lag_22,lag_21,lag_20,lag_19,lag_18,lag_17,lag_16,lag_15,lag_14,lag_13,lag_12,lag_11,lag_10,lag_9,lag_8,lag_7,lag_6,lag_5,lag_4,lag_3,lag_2,lag_1,n_taxi_rides
pickup_hour,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2022-01-02 04:00:00,1,4,4,1.791667,1.95,2.2500,1.000000,0.250,0.00,1.0,1.0,0.0,2.0,0.0,0.0,1.0,2.0,1.0,5.0,5.0,13.0,3.0,3.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022-01-02 05:00:00,1,5,1,1.750000,1.95,2.1875,0.750000,0.000,0.00,1.0,0.0,2.0,0.0,0.0,1.0,2.0,1.0,5.0,5.0,13.0,3.0,3.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
2022-01-02 06:00:00,1,6,1,1.875000,2.15,2.1250,0.833333,0.500,1.00,0.0,2.0,0.0,0.0,1.0,2.0,1.0,5.0,5.0,13.0,3.0,3.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0
2022-01-02 07:00:00,1,7,1,1.916667,2.15,1.8750,0.833333,0.625,1.25,2.0,0.0,0.0,1.0,2.0,1.0,5.0,5.0,13.0,3.0,3.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,2.0
2022-01-02 08:00:00,1,8,1,1.916667,2.15,1.1875,0.750000,0.875,1.75,0.0,0.0,1.0,2.0,1.0,5.0,5.0,13.0,3.0,3.0,1.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-30 19:00:00,265,19,3,3.708333,3.40,3.0000,3.083333,3.375,3.00,0.0,13.0,1.0,7.0,4.0,9.0,4.0,3.0,3.0,2.0,4.0,2.0,6.0,1.0,3.0,0.0,4.0,3.0,5.0,3.0,3.0,2.0,3.0,4.0,2.0
2022-09-30 20:00:00,265,20,3,3.791667,3.30,2.9375,2.750000,3.125,2.75,13.0,1.0,7.0,4.0,9.0,4.0,3.0,3.0,2.0,4.0,2.0,6.0,1.0,3.0,0.0,4.0,3.0,5.0,3.0,3.0,2.0,3.0,4.0,2.0,3.0
2022-09-30 21:00:00,265,21,4,3.375000,3.00,3.0000,2.916667,3.125,3.00,1.0,7.0,4.0,9.0,4.0,3.0,3.0,2.0,4.0,2.0,6.0,1.0,3.0,0.0,4.0,3.0,5.0,3.0,3.0,2.0,3.0,4.0,2.0,3.0,5.0
2022-09-30 22:00:00,265,22,4,3.541667,3.05,3.0625,3.083333,3.125,3.50,7.0,4.0,9.0,4.0,3.0,3.0,2.0,4.0,2.0,6.0,1.0,3.0,0.0,4.0,3.0,5.0,3.0,3.0,2.0,3.0,4.0,2.0,3.0,5.0,5.0
2022-09-30 23:00:00,265,23,4,3.458333,3.15,3.2500,3.500000,3.375,3.75,4.0,9.0,4.0,3.0,3.0,2.0,4.0,2.0,6.0,1.0,3.0,0.0,4.0,3.0,5.0,3.0,3.0,2.0,3.0,4.0,2.0,3.0,5.0,5.0,2.0

In [13]:
# test set
pd.concat((Xtest, ytest["n_taxi_rides"]), axis=1)

,pickup_location_id,hour,time_of_day,mean_lags_24_to_1,mean_lags_20_to_1,mean_lags_16_to_1,mean_lags_12_to_1,mean_lags_8_to_1,mean_lags_4_to_1,lag_24,lag_23,lag_22,lag_21,lag_20,lag_19,lag_18,lag_17,lag_16,lag_15,lag_14,lag_13,lag_12,lag_11,lag_10,lag_9,lag_8,lag_7,lag_6,lag_5,lag_4,lag_3,lag_2,lag_1,n_taxi_rides
pickup_hour,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2022-10-01 04:00:00,1,4,4,1.291667,1.55,1.8750,2.000000,2.125,1.50,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0,1.0,0.0,4.0,2.0,1.0,4.0,4.0,0.0,3.0,4.0,1.0,0.0,1.0,2.0
2022-10-01 05:00:00,1,5,1,1.375000,1.65,2.0000,2.166667,1.875,1.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0,1.0,0.0,4.0,2.0,1.0,4.0,4.0,0.0,3.0,4.0,1.0,0.0,1.0,2.0,2.0
2022-10-01 06:00:00,1,6,1,1.458333,1.75,2.0000,2.000000,1.625,1.25,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0,1.0,0.0,4.0,2.0,1.0,4.0,4.0,0.0,3.0,4.0,1.0,0.0,1.0,2.0,2.0,1.0
2022-10-01 07:00:00,1,7,1,1.500000,1.80,1.8750,1.916667,1.750,1.50,0.0,0.0,0.0,0.0,1.0,0.0,2.0,3.0,1.0,0.0,4.0,2.0,1.0,4.0,4.0,0.0,3.0,4.0,1.0,0.0,1.0,2.0,2.0,1.0,0.0
2022-10-01 08:00:00,1,8,1,1.500000,1.75,1.8125,1.833333,1.375,1.25,0.0,0.0,0.0,1.0,0.0,2.0,3.0,1.0,0.0,4.0,2.0,1.0,4.0,4.0,0.0,3.0,4.0,1.0,0.0,1.0,2.0,2.0,1.0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-31 19:00:00,265,19,3,3.291667,3.50,3.0625,2.916667,3.250,3.25,2.0,5.0,1.0,1.0,7.0,3.0,5.0,6.0,3.0,2.0,3.0,6.0,2.0,0.0,5.0,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0
2022-12-31 20:00:00,265,20,3,3.291667,3.25,3.0000,2.916667,2.875,2.75,5.0,1.0,1.0,7.0,3.0,5.0,6.0,3.0,2.0,3.0,6.0,2.0,0.0,5.0,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2.0
2022-12-31 21:00:00,265,21,4,3.166667,3.20,3.0000,3.083333,2.875,2.75,1.0,1.0,7.0,3.0,5.0,6.0,3.0,2.0,3.0,6.0,2.0,0.0,5.0,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2.0,7.0
2022-12-31 22:00:00,265,22,4,3.416667,3.30,3.2500,3.250000,3.500,3.50,1.0,7.0,3.0,5.0,6.0,3.0,2.0,3.0,6.0,2.0,0.0,5.0,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2.0,7.0,3.0
2022-12-31 23:00:00,265,23,4,3.500000,3.15,3.0625,3.333333,3.375,3.50,7.0,3.0,5.0,6.0,3.0,2.0,3.0,6.0,2.0,0.0,5.0,2.0,5.0,2.0,2.0,4.0,4.0,2.0,4.0,3.0,2.0,2.0,7.0,3.0,2.0

#### **Model training and selection**

**`Combine data ingestion, transformation, and train-test split into a single step`**

In [14]:
Xtrain, ytrain, Xtest, ytest = (
    ingest_data(2022)
    .pipe(transform_data)
    .pipe(split_data, "2022-10-01")
)

100%|██████████| 12/12 [00:00<00:00, 1020.12it/s]
100%|██████████| 262/262 [00:16<00:00, 16.12it/s]

In [ ]:
# this is an alternative way of combining data ingestion, transformation, and train-test split ...
# into a single step using scikit-learn's 'make_pipeline' function and 'FunctionTransformer' class
pl = make_pipeline(
    FunctionTransformer(ingest_data, validate=False), 
    FunctionTransformer(transform_data, validate=False), 
    FunctionTransformer(split_data, kw_args={"split_date": "2022-10-01"}, validate=False),
)
Xtrain, ytrain, Xtest, ytest = pl.fit_transform(2022)

**`BaselineModel, XGBRegressor, CatBoostRegressor, LGBMRegressor`**

In [15]:
# model dictionary
models: dict[str, BaselineModel | CatBoostRegressor | LGBMRegressor | XGBRegressor] = {
    "BaselineModel": BaselineModel(), 
    "CatBoostRegressor": CatBoostRegressor(
        loss_function="RMSE", n_estimators=100, silent=True, thread_count=-1
    ), 
    "LGBMRegressor": LGBMRegressor(objective="rmse", verbose=-1, n_jobs=-1),
    "XGBRegressor": XGBRegressor(objective="reg:squarederror", n_jobs=-1)
}

# a dictionary to map each model to its test set R²
report: dict[str, float] = {}
for model_name, model in tqdm(models.items()):
    model.fit(Xtrain.drop("pickup_location_id", axis=1), ytrain["n_taxi_rides"])
    test_metric: float = get_rsquared(
        ytest["n_taxi_rides"], model.predict(Xtest.drop("pickup_location_id", axis=1))
    )
    report[model_name] = round(test_metric, 4)

# sort the 'report' dictionary based on the test set R²
dict(sorted(report.items(), key=lambda kv: kv[1], reverse=True))

100%|██████████| 4/4 [00:28<00:00,  7.12s/it]

{'XGBRegressor': 0.9719,
 'LGBMRegressor': 0.9716,
 'CatBoostRegressor': 0.9713,
 'BaselineModel': 0.9329}

In [16]:
# create the transformed data
df_transformed: pd.DataFrame = ingest_data(2022).pipe(transform_data)

# extract the model
reg = train_model(df_transformed, "2022-09-01")
reg

100%|██████████| 12/12 [00:00<00:00, 953.67it/s]
100%|██████████| 262/262 [00:15<00:00, 16.65it/s]
100%|██████████| 4/4 [00:25<00:00,  6.43s/it]

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=-1,
             num_parallel_tree=None, random_state=None, ...)

#### **Recursive forecast**

In [ ]:
# create the transformed data, that is, tabular data with features and a target 
df_transformed: pd.DataFrame = ingest_data(2022).pipe(transform_data)
df_transformed

In [ ]:
# a list containing the most-active pickup location IDs
location_ids: list[int] = [
    loc_id for loc_id in sorted(df_transformed["pickup_location_id"].unique()) 
    if df_transformed.query(f"pickup_location_id == {loc_id}")["n_taxi_rides"].mean() > 50
]

# create an 'LGBMRegressor' instance
reg: LGBMRegressor = LGBMRegressor(objective="rmse", verbose=-1, n_jobs=-1)

In [ ]:
# get the location ID, starting date, and ending date
location_id: int = random.choice(location_ids)
dates: list[date] = sorted(set(
    ts.date() for ts in df_transformed.query(f"pickup_location_id == {location_id}").index
))
start: date = random.choice(dates[:-8])
end: date = start + pd.Timedelta(days=7)

# filter the in-sample data based on the location ID, starting date, and ending date
df_temp: pd.DataFrame = (
    df_transformed
    .loc[
        (df_transformed["pickup_location_id"] == location_id) &
        (df_transformed.index >= str(start)) & 
        (df_transformed.index < str(end))
    ]
    .drop("pickup_location_id", axis=1)
)

# feature matrix and target vector
X, y = df_temp.drop("n_taxi_rides", axis=1), df_temp["n_taxi_rides"]

# fit the 'LGBMRegressor' instance to the feature matrix and target vector
reg.fit(X.values, y.values)

In [ ]:
# create the out-of-sample timestamps
forecast_indices: pd.DatetimeIndex = pd.date_range(
    X.index[-1] + pd.Timedelta(hours=1), X.index[-1] + pd.Timedelta(hours=24), freq="H"
)

# create the out-of-sample datetime features
hours: list[int] = [ts.hour for ts in forecast_indices]
time_of_day: list[int] = [
    1 if hour in range(5, 12)
    else 2 if hour in range(12, 17)
    else 3 if hour in range(17, 21)
    else 4 for hour in hours
]
x_dts: list[list[int]] = [list(t) for t in list(zip(hours, time_of_day))]

# create the lag features for the 1st input
lag_cols: list[str] = [col for col in X.columns if col.startswith("lag")]
x_lag: list[float] = X.iloc[-1][lag_cols].tolist()[1:] + [y.iloc[-1]]

# create the window features for the 1st input
x_window: list[float] = [np.array(x_lag)[i:].mean() for i in range(-len(lag_cols), 0, 4)]

# create the 1st input
x: np.ndarray = np.array(x_dts[0] + x_window + x_lag)

# get the 1st prediction and add it a list named, 'predictions'
yhat: float = max(reg.predict(x.reshape(1, -1))[0], 0)
predictions: list[float] = [yhat]

# get the remaining predictions and append each to the 'predictions' list
for x_dt in x_dts[1:]:
    x_lag = x_lag[1:] + [yhat]
    x_window = [np.array(x_lag)[i:].mean() for i in range(-len(lag_cols), 0, 4)]
    x = np.array(x_dt + x_window + x_lag)
    yhat = max(reg.predict(x.reshape(1, -1))[0], 0)
    predictions.append(yhat)

# # recursive forecast
# forecast: pd.Series = pd.Series(predictions, index=forecast_indices)

In [ ]:
# pd.DataFrame that contains the out-of-sample target and recursive forecast
df_future: pd.DataFrame = (
    df_transformed
    .query(f"pickup_location_id == {location_id}")
    .loc[forecast_indices]
    .assign(forecast=predictions)
    .rename({"n_taxi_rides": "target"}, axis=1)
    [["target", "forecast"]]
)

# output the R² between the out-of-sample target and recursive forecast
print(f"R²: {get_rsquared(df_future['target'], df_future['forecast']):.2f}")

# plot the out-of-sample target and recursive forecast 
fig: Figure = px.line(
    df_future,
    x=df_future.index, 
    y=["target", "forecast"], 
    color_discrete_map={"target": "green", "forecast": "red"},
    labels={"index": "Datetime", "value": "Number of taxi rides", "variable": ""},
    template="plotly_dark", 
    markers=True, 
    title=f"Hourly taxi rides for pickup location {location_id}"
)
fig.show()